BEGIN
	DBMS_OUTPUT.PUT_LINE('HELLO WORLD!');
END;

DECLARE
	NUM1 NUMBER := 10;
	NUM2 NUMBER := 20;
	ANS NUMBER;
BEGIN
	ANS := NUM1+NUM2;
	DBMS_OUTPUT.PUT_LINE('THE ADDITION IS = '||ANS);
	DBMS_OUTPUT.PUT_LINE('THE SUBTRACTION IS = '||(NUM1-NUM2));
	DBMS_OUTPUT.PUT_LINE('THE MULTIPLICATION IS = '||(NUM1*NUM2));
	DBMS_OUTPUT.PUT_LINE('THE DIVISION IS = '||(NUM1/NUM2));
	DBMS_OUTPUT.PUT_LINE('THE REMAINDER IS = '||MOD(NUM1,NUM2));
END;

DECLARE -- FIRST BLOCK
	X NUMBER := 10;
		BEGIN
			DECLARE -- SECOND BLOCK
				Y NUMBER := 20;
					BEGIN
						DECLARE -- THIRD BLOCK
							Z NUMBER := 30;
								BEGIN
                                    DBMS_OUTPUT.PUT_LINE('THIRD BLOCK := ');
									DBMS_OUTPUT.PUT_LINE('VALUE OF X = '||X);
									DBMS_OUTPUT.PUT_LINE('VALUE OF Y = '||Y);
									DBMS_OUTPUT.PUT_LINE('VALUE OF Z = '||Z);
								END;
						DBMS_OUTPUT.PUT_LINE('SECOND BLOCK := ');
						DBMS_OUTPUT.PUT_LINE('VALUE OF X = '||X);
						DBMS_OUTPUT.PUT_LINE('VALUE OF Y = '||Y);
					END;
			DBMS_OUTPUT.PUT_LINE('FIRST BLOCK := ');
			DBMS_OUTPUT.PUT_LINE('VALUE OF X = '||X);
		END;

-- CONDITIONAL STATEMENTS
DECLARE 
	AGE NUMBER := 8;
BEGIN
	IF AGE>18 THEN
		DBMS_OUTPUT.PUT_LINE('YOU ARE ELIGIBLE FOR VOTING');
	ELSE
		DBMS_OUTPUT.PUT_LINE('YOU ARE NOT ELIGIBLE FOR VOTING');
	END IF;
END;

DECLARE
	NUM1 NUMBER := 20;
	NUM2 NUMBER := 10;
BEGIN
	IF NUM1>NUM2 THEN
		DBMS_OUTPUT.PUT_LINE(NUM1||' IS THE BIGGEST NUMBER');
	ELSIF NUM1=NUM2 THEN
        DBMS_OUTPUT.PUT_LINE('BOTH NUMBERS ARE EQUAL');
	ELSE
		DBMS_OUTPUT.PUT_LINE(NUM2||' IS THE BIGGEST NUMBER');
	END IF;
END;

DECLARE 
	NUM1 NUMBER := 10;
	NUM2 NUMBER := 20;
	NUM3 NUMBER := 30;
BEGIN
	IF NUM1>NUM2 AND NUM1>NUM3 THEN
		DBMS_OUTPUT.PUT_LINE(NUM1||' IS THE BIGGEST NUMBER');
	ELSIF NUM2>NUM1 AND NUM2>NUM3 THEN
		DBMS_OUTPUT.PUT_LINE(NUM2||' IS THE BIGGEST NUMBER');
	ELSE
		DBMS_OUTPUT.PUT_LINE(NUM3||' IS THE BIGGEST NUMBER');
	END IF;
END;

-- SIMPLE LOOP
DECLARE
	I NUMBER := 1;
BEGIN
	LOOP
		DBMS_OUTPUT.PUT_LINE('TOPS Technologies');
		IF I=5 THEN
			EXIT;
		END IF;
		I := I + 1;
	END LOOP;
END;

-- SIMPLE LOOP
DECLARE
	I NUMBER := 1;
BEGIN
	LOOP
		DBMS_OUTPUT.PUT_LINE('TOPS Technologies');
			EXIT WHEN I=5;
		I := I + 1;
	END LOOP;
END;

-- FOR LOOP
BEGIN 
	FOR X IN 1..5 LOOP
		DBMS_OUTPUT.PUT_LINE('TOPS Technologies');
	END LOOP;
END;

-- FOR LOOP
DECLARE 
	X NUMBER := 1;
BEGIN
	FOR I IN 1..5 LOOP
		DBMS_OUTPUT.PUT_LINE(X);
		X := X + 1;
	END LOOP;
END;

-- WHILE LOOP
DECLARE 
	X NUMBER := 1;
BEGIN
	WHILE X<=5 LOOP
		DBMS_OUTPUT.PUT_LINE('TOPS Technologies');
		X := X + 1;
	END LOOP;
END;