CREATE SCHEMA EMP;

CREATE TABLE EMPLOYEES
(
EMPLOYEE_ID INT NOT NULL UNIQUE,
FIRST_NAME VARCHAR(15) NOT NULL,
LAST_NAME VARCHAR(15) NOT NULL,
EMAIL VARCHAR(50) NOT NULL,
HIRE_DATE DATE NOT NULL,
SALARY INT NOT NULL,
COMMISSION_PCT FLOAT,
MANAGER_ID INT,
DEPARTMENT_ID INT
);

DESCRIBE EMPLOYEES;

-- ALTER COMMAND
-- RENAME TABLE
ALTER TABLE EMPLOYEES RENAME TO EMP_DATA; 
ALTER TABLE EMP_DATA RENAME TO EMPLOYEES;

-- MODIFY
ALTER TABLE EMPLOYEES MODIFY COMMISSION_PCT INT NOT NULL;
ALTER TABLE EMPLOYEES MODIFY COMMISSION_PCT FLOAT;

-- ADD COLUMN
ALTER TABLE EMPLOYEES ADD COLUMN JOB_ID VARCHAR(45) NOT NULL;

-- ADD COLUMN AFTER SPECIFIC COLUMN
ALTER TABLE EMPLOYEES ADD COLUMN JOB_ID VARCHAR(45) NOT NULL AFTER SALARY;

-- RENAME COLUMN
ALTER TABLE EMPLOYEES RENAME COLUMN EMPLOYEE_ID TO EMP_ID;

-- DELETE COLUMN
ALTER TABLE EMPLOYEES DROP COLUMN JOB_ID;

-- TO DROP THE TABLE
DROP TABLE EMPLOYEES;

-- TO DROP THE SCHEMA
DROP SCHEMA EMP;

SELECT * FROM EMPLOYEES;

COMMIT;